In [1]:
import pandas as pd
import requests as ro
from bs4 import BeautifulSoup as bs



import numpy as np

In [3]:
data_url = pd.read_html("http://www.nepalstock.com/main/stockwiseprices/index/2/?startDate=2000-01-17&endDate=&stock-symbol=130&_limit=20000000")

In [4]:
url = "http://www.nepalstock.com/main/stockwiseprices/index/2/?startDate=2000-01-17&endDate=&stock-symbol=131&_limit=20000000"
data_string = url.split("/")[-1:]

In [5]:
data_file = pd.read_csv("/home/sanjay/Downloads/id - Sheet.csv", header= None   )
data_file.rename(columns={0:'Id', 1: 'Name'}, inplace= True)

data_file

       Id   Name
0     131  NABIL
1     132    NIB
2     133    SCB
3     134    NaN
4     135    SBI
..    ...    ...
421  2914   UMRH
422  2915    PLI
423  2917    CGH
424  2919  NIFRA
425   156    BBC

[426 rows x 2 columns]

In [6]:
#data_file.loc[0].dtypes
#data_file.loc[0].astype(int)

In [7]:
data_file['Id'].value_counts()

156     2
131     1
712     1
726     1
725     1
       ..
400     1
398     1
397     1
396     1
2919    1
Name: Id, Length: 425, dtype: int64

In [8]:
var_1 = data_file.loc[:,["Id" ]]
d = {}

for  index_value in range(len(var_1)):
      url_id = var_1.loc[index_value,"Id"]
      
      url = "http://www.nepalstock.com/main/stockwiseprices/index/2/?startDate=2000-01-17&endDate=&stock-symbol="+str(url_id)+"&_limit=20000000"
      #print(url)
      d[url_id] = pd.read_html(url)
      
      

      #print(index_value)
#var_1.loc[5]
print(d)
#print(var_1.dtyes)

{131: [                                                      0  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                                  S.N.
2                                                     1
3                                                     2
4                                                     3
...                                                 ...
2597                                               2596
2598                                               2597
2599                                               2598
2600                                               2599
2601                                         Page 1/1 1

                                                      1  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                                  Date
2                                            2021-10-11
3                                            2021-10-10
4                                            2021-10-06
...                                                 ...
2597                                         2010-04-19
2598                                         2010-04-15
2599                                         2010-04-15
2600                                         2010-04-15
2601                                         Page 1/1 1

                                                      2  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                    Total Transactions
2                                                  1430
3                                                  1074
4                                                   885
...                                                 ...
2597                                                 18
2598                                                 40
2599                                                 40
2600                                                 40
2601                                         Page 1/1 1

                                                      3  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                   Total Traded Shares
2                                             118043.00
3                                              77855.00
4                                              57353.00
...                                                 ...
2597                                            1774.00
2598                                            3464.00
2599                                            3464.00
2600                                            3464.00
2601                                         Page 1/1 1

                                                      4  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                   Total Traded Amount
2                                          171385318.30
3                                          114755872.10
4                                           82656811.90
...                                                 ...
2597                                         3549542.00
2598                                         6935470.00
2599                                         6935470.00
2600                                         6935470.00
2601                                         Page 1/1 1

                                                      5  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                            Max. Price
2                                               1503.00
3                                               1500.00
4                                               1453.00
...                                                 ...
2597                                            2039.00
2598                                            2040.00
2599                                            2040.00
2600                                            2040.00
2601                                         Page 1/1 1

                                                      6  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                            Min. Price
2                                               1439.90
3                                               1462.60
4                                               1410.00
...                                                 ...
2597                                            2000.00
2598                                            2000.00
2599                                            2000.00
2600                                            2000.00
2601                                         Page 1/1 1

                                                      7  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                           Close Price
2                                               1450.00
3                                               1474.00
4                                               1444.90
...                                                 ...
2597                                            2001.00
2598                                            2000.00
2599                                            2000.00
2600                                            2000.00
2601                                                NaN

                                                      8  \
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
2597                                                NaN
2598                                                NaN
2599                                                NaN
2600                                                NaN
2601                                                NaN

                                                      9
0     Nabil Bank Limited Start Date  End Date  Stock...
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
2597                                                NaN
2598                                                NaN
2599                                                NaN
2600                                                NaN
2601                                                NaN

[2602 rows x 10 columns]], 132: [                                                      0  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                                  S.N.
2                                                     1
3                                                     2
4                                                     3
...                                                 ...
2497                                               2496
2498                                               2497
2499                                               2498
2500                                               2499
2501                                         Page 1/1 1

                                                      1  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                                  Date
2                                            2021-05-13
3                                            2021-05-12
4                                            2021-05-11
...                                                 ...
2497                                         2010-04-19
2498                                         2010-04-15
2499                                         2010-04-15
2500                                         2010-04-15
2501                                         Page 1/1 1

                                                      2  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                    Total Transactions
2                                                  2862
3                                                   420
4                                                   310
...                                                 ...
2497                                                  7
2498                                                  5
2499                                                  5
2500                                                  5
2501                                         Page 1/1 1

                                                      3  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                   Total Traded Shares
2                                             395752.00
3                                              55626.00
4                                              26068.00
...                                                 ...
2497                                             709.00
2498                                             484.00
2499                                             484.00
2500                                             484.00
2501                                         Page 1/1 1

                                                      4  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                   Total Traded Amount
2                                          183411016.00
3                                           25044238.00
4                                           11702048.00
...                                                 ...
2497                                          469072.00
2498                                          328884.00
2499                                          328884.00
2500                                          328884.00
2501                                         Page 1/1 1

                                                      5  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                            Max. Price
2                                                484.00
3                                                456.00
4                                                451.00
...                                                 ...
2497                                             670.00
2498                                             693.00
2499                                             693.00
2500                                             693.00
2501                                         Page 1/1 1

                                                      6  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                            Min. Price
2                                                455.00
3                                                448.00
4                                                444.00
...                                                 ...
2497                                             658.00
2498                                             671.00
2499                                             671.00
2500                                             671.00
2501                                         Page 1/1 1

                                                      7  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                           Close Price
2                                                460.00
3                                                453.00
4                                                449.00
...                                                 ...
2497                                             659.00
2498                                             671.00
2499                                             671.00
2500                                             671.00
2501                                                NaN

                                                      8  \
0     Nepal Investment Bank Limited Start Date  End ...
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
2497                                                NaN
2498                                                NaN
2499                                                NaN
2500                                                NaN
2501                                                NaN

                                                      9
0     Nepal Investment Bank Limited Start Date  End ...
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
2497                                                NaN
2498                                                NaN
2499                                                NaN
2500                                                NaN
2501                                                NaN

[2502 rows x 10 columns]], 133: [                                                      0  \
0     Standard Chartered Bank Limited Start Date  En...
1                                                  S.N.
2                                                     1
3                                                     2
4                                                     3
...                                                 ...
2608                                               2607
2609                                               2608
2610                                               2609
2611                                               2610
2612                                         Page 1/1 1

                                                      1  \
0     Standard Chartered Bank Limited Start Date  En...
1                                                  Date
2                                            2021-10-11
3                                            2021-10-10
4                                            2021-10-06
...                                                 ...
2608                                         2010-04-19
2609                                         2010-04-15
2610                                         2010-04-15
2611                                         2010-04-15
2612                                         Page 1/1 1

                                                      2  \
0     Standard Chartered Bank Limited Start Date  En...
1                                    Total Transactions
2                                                    83
3                                                   105
4                                                   263
...                                                 ...
2608                                                 16
2609                                                  9
2610                                                  9
2611                                                  9
2612                                         Page 1/1 1

                                                      3  \
0     Standard Chartered Bank Limited Start Date  En...
1                                   Total Traded Shares
2                                               7064.00
3                                               7862.00
4                                              23461.00
...                                                 ...
2608                                             587.00
2609                                             693.00
2610                                             693.00
2611                                             693.00
2612                                         Page 1/1 1

                                                      4  \
0     Standard Chartered Bank Limited Start Date  En...
1                                   Total Traded Amount
2                                            3796669.10
3                                            4245497.00
4                                           12618253.50
...                                                 ...
2608                                         1642908.00
2609                                         1968110.00
2610                                         1968110.00
2611                                         1968110.00
2612                                         Page 1/1 1

                                                      5  \
0     Standard Chartered Bank Limited Start Date  En...
1                                            Max. Price
2                                                540.00
3                                                547.00
4                                                550.00
...                                                 ...
2608                                            2830.00
2609                                            2850.00
2610                                            2850.00
2611                                            2850.00
2612                                         Page 1/1 1

                                                      6  \
0     Standard Chartered Bank Limited Start Date  En...
1                                            Min. Price
2                                                535.00
3                                                536.00
4                                                532.40
...                                                 ...
2608                                            2790.00
2609                                            2825.00
2610                                            2825.00
2611                                            2825.00
2612                                         Page 1/1 1

                                                      7  \
0     Standard Chartered Bank Limited Start Date  En...
1                                           Close Price
2                                                535.00
3                                                537.00
4                                                536.90
...                                                 ...
2608                                            2801.00
2609                                            2831.00
2610                                            2831.00
2611                                            2831.00
2612                                                NaN

                                                      8  \
0     Standard Chartered Bank Limited Start Date  En...
1                                                   NaN
2                                                   NaN
3                                                   NaN
4                                                   NaN
...                                                 ...
2608                                                NaN
2609                                                NaN
2610                                                NaN
2611                                                NaN
2612                                                NaN

                                                      9
0     Standard Chartered Bank Limited Start Date  En...
1                                                   NaN
2                                                   NaN
3                                                   NaN

In [ ]:
import mysql.connector
from mysql.connector import Error

In [ ]:
try:
    connection = mysql.connector.connect(host='localhost',
                                         database='testdb',
                                         user='root',
                                         password='Manandhar123$')
    
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor()
        cursor.execute("select database();")
        record = cursor.fetchone()
        print("You're connected to database: ", record)

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if connection.is_connected():
        #cursor.close()
        #connection.close()
        #print("MySQL connection is closed")
        pass

In [ ]:
select_table_compay = "SELECT * From company"
with connection.cursor() as cursor:
  cursor.execute(select_table_compay)
  for row in cursor.fetchall():
     print(row)

In [ ]:
select_fetch_nepse_id ='select nepse_company_id From company'
with connection.cursor() as cursor:
  cursor.execute(select_fetch_nepse_id)
  for row in cursor.fetchall():
     print(row)

In [14]:
for key in d.keys():
    a = key
    print(a)

131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
151
152
153
154
155
156
158
159
160
163
164
166
171
172
174
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
192
194
195
198
200
201
203
204
205
207
209
210
211
213
215
217
219
221
222
226
227
228
230
231
232
233
235
236
238
242
244
245
249
250
255
256
259
261
263
268
273
274
277
280
281
282
283
286
288
289
291
292
296
298
299
307
309
311
312
313
314
315
319
327
330
338
339
341
346
347
348
350
352
354
355
357
358
359
360
361
362
371
380
385
387
390
391
393
396
397
398
400
401
403
417
418
419
420
421
427
428
440
441
447
449
450
451
456
459
469
471
472
473
474
479
487
488
490
493
496
502
505
511
516
517
522
532
544
545
559
561
562
564
568
573
574
575
576
577
579
581
582
583
587
589
590
591
592
593
594
598
599
601
602
605
606
607
608
609
610
612
613
615
616
618
619
620
621
623
624
625
626
628
630
631
632
634
635
636
637
639
640
643
644
648
649
650
651
652
653
654
655
656
657
658
659
661
663
669
670
671
672
673
674
676
677
678
682
684
685
686
687
689
691
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
710
711
712
713
714
716
719
720
721
722
723
725
726
729
730
731
732
733
1736
1737
1739
1740
1741
1742
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2792
2804
2806
2807
2809
2810
2811
2812
2813
2815
2816
2824
2825
2826
2828
2829
2831
2832
2834
2835
2840
2841
2842
2843
2845
2846
2850
2851
2852
2854
2855
2856
2859
2860
2861
2862
2863
2864
2867
2868
2869
2870
2871
2872
2873
2875
2877
2878
2880
2881
2882
2885
2887
2889
2890
2892
2893
2895
2896
2898
2900
2902
2903
2904
2905
2907
2908
2911
2912
2913
2914
2915
2917
2919

In [ ]:
from sqlalchemy import create_engine
df = pd.DataFrame.from_dict(d)
engine = create_engine('mysql+pymysql://user:passwd@host:port/name').connect()
df.to_sql('ohlc', con=engine, if_exists='replace')

In [ ]:
df[for i in 0].values

In [ ]:
inserting_ohlc_values ='''INSERT INTO OHLC(company_id) VALUES(%s); '''
record_to_insert=[(key)]
with connection.cursor() as cursor:
    cursor.execute(inserting_ohlc_values, record_to_insert)
    connection.commit()

In [ ]:
d